export enum TransferOperation {
  CoreSend = 'coreSend',
  AssetLockFunding = 'assetLockFunding',
  AssetLockShield = 'assetLockShield',
  IdentityRegister = 'identityRegister',
  IdentityTopUpL1 = 'identityTopUpL1',
  AddressFundsTransfer = 'addressFundsTransfer',
  IdentityTopUp = 'identityTopUp',
  IdentityCreate = 'identityCreate',
  AddressWithdrawal = 'addressWithdrawal',
  Shield = 'shield',
  IdentityToAddress = 'identityToAddress',
  IdentityToIdentity = 'identityToIdentity',
  IdentityWithdrawal = 'identityWithdrawal',
  ShieldedTransfer = 'shieldedTransfer',
  Unshield = 'unshield',
  ShieldedWithdrawal = 'shieldedWithdrawal',
  IdentityCreateFromPool = 'identityCreateFromPool',
}
