export const apiDefinitions = (ipcRenderer) => ({
  createWallet: (seedphrase: string, network: string, password: string) => ipcRenderer.invoke('createWallet', seedphrase, network, password),
  deleteWallet: (walletId: string) => ipcRenderer.invoke('deleteWallet', walletId),
  verifyWalletPassword: (walletId: string, password: string) => ipcRenderer.invoke('verifyWalletPassword', walletId, password),
  exportMnemonic: (walletId: string, password: string): Promise<string> => ipcRenderer.invoke('exportMnemonic', walletId, password),
  getAddresses: (walletId: string) => ipcRenderer.invoke('getAddresses', walletId),
  addWalletAddress: (walletId: string, password: string, isChange: boolean) => ipcRenderer.invoke('addWalletAddress', walletId, password, isChange),
  getReceiveAddress: (walletId: string) => ipcRenderer.invoke('getReceiveAddress', walletId),
  getStatus: () => ipcRenderer.invoke('getStatus'),
  selectWallet: (walletId: string) => ipcRenderer.invoke('selectWallet', walletId),
  getAllWallets: () => ipcRenderer.invoke('getAllWallets'),
  getTransactions: (walletId: string) => ipcRenderer.invoke('getTransactions', walletId),
  getTransactionByHash: (hash: string, network: string) => ipcRenderer.invoke('getTransactionByHash', hash, network),
  getBlockByHash: (hash: string, network: string) => ipcRenderer.invoke('getBlockByHash', hash, network),
  getBalance: (address: string | string[], network: string) => ipcRenderer.invoke('getBalance', address, network),
  getWalletBalance: (walletId: string) => ipcRenderer.invoke('getWalletBalance', walletId),
  getIdentities: (walletId: string) => ipcRenderer.invoke('getIdentities', walletId),
  getIdentityBalance: (identifier: string): Promise<bigint> => ipcRenderer.invoke('getIdentityBalance', identifier),
  getIdentityNonce: (identifier: string): Promise<bigint> => ipcRenderer.invoke('getIdentityNonce', identifier),
  getPlatformAddresses: (walletId: string) => ipcRenderer.invoke('getPlatformAddresses', walletId),
  addPlatformAddress: (walletId: string) => ipcRenderer.invoke('addPlatformAddress', walletId),
  setAddressLabel: (walletId: string, address: string, label: string) => ipcRenderer.invoke('setAddressLabel', walletId, address, label),
  setWalletLabel: (walletId: string, label: string | null) => ipcRenderer.invoke('setWalletLabel', walletId, label),
  sendTransaction: (walletId: string, toAddress: string, amountDuffs: string, password: string, fromAddress?: string) => ipcRenderer.invoke('sendTransaction', walletId, toAddress, amountDuffs, password, fromAddress),
  getTxLockStatus: (walletId: string, txid: string) => ipcRenderer.invoke('getTxLockStatus', walletId, txid),
  sendPlatformTransfer: (walletId: string, fromAddress: string, toAddress: string, amountCredits: string, password: string) => ipcRenderer.invoke('sendPlatformTransfer', walletId, fromAddress, toAddress, amountCredits, password),
  topUpIdentityFromAddresses: (walletId: string, identityId: string, fromAddress: string | null, amountCredits: string, password: string) => ipcRenderer.invoke('topUpIdentityFromAddresses', walletId, identityId, fromAddress, amountCredits, password),
  withdrawPlatformCredits: (walletId: string, fromAddress: string | null, toCoreAddress: string, amountCredits: string, password: string) => ipcRenderer.invoke('withdrawPlatformCredits', walletId, fromAddress, toCoreAddress, amountCredits, password),
  sendIdentityCredits: (walletId: string, identityId: string, toAddress: string, amountCredits: string, password: string) => ipcRenderer.invoke('sendIdentityCredits', walletId, identityId, toAddress, amountCredits, password),
  transferIdentityCredits: (walletId: string, fromIdentityId: string, toIdentityId: string, amountCredits: string, password: string) => ipcRenderer.invoke('transferIdentityCredits', walletId, fromIdentityId, toIdentityId, amountCredits, password),
  withdrawIdentityCredits: (walletId: string, identityId: string, toCoreAddress: string, amountCredits: string, password: string) => ipcRenderer.invoke('withdrawIdentityCredits', walletId, identityId, toCoreAddress, amountCredits, password),
  createIdentityFromAddresses: (walletId: string, fromAddress: string | null, amountCredits: string, password: string) => ipcRenderer.invoke('createIdentityFromAddresses', walletId, fromAddress, amountCredits, password),
  startAssetLockFunding: (walletId: string, toPlatformAddress: string, amountDuffs: string, password: string, kind?: string) => ipcRenderer.invoke('startAssetLockFunding', walletId, toPlatformAddress, amountDuffs, password, kind),
  getAssetLockFundingState: (walletId: string) => ipcRenderer.invoke('getAssetLockFundingState', walletId),
  resumeAssetLockFunding: (walletId: string, password: string) => ipcRenderer.invoke('resumeAssetLockFunding', walletId, password),
  shieldToPool: (walletId: string, fromAddress: string, toAddress: string, amountCredits: string, password: string) => ipcRenderer.invoke('shieldToPool', walletId, fromAddress, toAddress, amountCredits, password),
  // preferencess
  getPreferences: () => ipcRenderer.invoke('getPreferences'),
  setLanguage: (language: string) => ipcRenderer.invoke('setLanguage', language),
  setFiatCurrency: (currency: string) => ipcRenderer.invoke('setFiatCurrency', currency),
  setConnectionType: (connectionType: 'p2p' | 'rpc') => ipcRenderer.invoke('setConnectionType', connectionType),
  resetPreferences: () => ipcRenderer.invoke('resetPreferences'),

  startWalletSync: (walletId: string) => ipcRenderer.invoke('startWalletSync', walletId),
  stopWalletSync: () => ipcRenderer.invoke('stopWalletSync'),
  resetWalletSync: (network: 'mainnet' | 'testnet') => ipcRenderer.invoke('resetWalletSync', network),
  getUtxos: () => ipcRenderer.invoke('getUtxos'),
  hasSyncProgress: (walletId: string) => ipcRenderer.invoke('hasSyncProgress', walletId),
  broadcastTransaction: (txHex: string) => ipcRenderer.invoke('broadcastTransaction', txHex),

  getExchangeRates: () => ipcRenderer.invoke('getExchangeRates'),

  saveTextFile: (defaultFileName: string, content: string) => ipcRenderer.invoke('saveTextFile', defaultFileName, content),

  getContacts: (network?: 'mainnet' | 'testnet') => ipcRenderer.invoke('getContacts', network),
  addContact: (label: string, address: string, network: 'mainnet' | 'testnet') => ipcRenderer.invoke('addContact', label, address, network),
  deleteContact: (id: number) => ipcRenderer.invoke('deleteContact', id),

  getShieldedStatus: () => ipcRenderer.invoke('getShieldedStatus'),
  getShieldedPoolInfo: (network: 'mainnet' | 'testnet') => ipcRenderer.invoke('getShieldedPoolInfo', network),
  startShieldedSync: (walletId: string, password: string) => ipcRenderer.invoke('startShieldedSync', walletId, password),
  getShieldedSyncState: (walletId: string) => ipcRenderer.invoke('getShieldedSyncState', walletId),
  startShieldedTransfer: (walletId: string, recipient: string, amountCredits: string, password: string, noteIndex?: number) => ipcRenderer.invoke('startShieldedTransfer', walletId, recipient, amountCredits, password, noteIndex),
  startShieldedUnshield: (walletId: string, outputAddress: string, amountCredits: string, password: string, noteIndex?: number) => ipcRenderer.invoke('startShieldedUnshield', walletId, outputAddress, amountCredits, password, noteIndex),
  startShieldedWithdrawal: (walletId: string, coreAddress: string, amountCredits: string, password: string, noteIndex?: number) => ipcRenderer.invoke('startShieldedWithdrawal', walletId, coreAddress, amountCredits, password, noteIndex),
  startShieldedIdentityCreate: (walletId: string, denominationCredits: string, password: string) => ipcRenderer.invoke('startShieldedIdentityCreate', walletId, denominationCredits, password),
  getShieldedSpendState: (walletId: string) => ipcRenderer.invoke('getShieldedSpendState', walletId),
  getShieldedAddress: (walletId: string, password?: string) => ipcRenderer.invoke('getShieldedAddress', walletId, password),
  getShieldedAddresses: (walletId: string, password?: string) => ipcRenderer.invoke('getShieldedAddresses', walletId, password),
  addShieldedAddress: (walletId: string, password: string) => ipcRenderer.invoke('addShieldedAddress', walletId, password),
})
